name: 'Terraform'

on: [push, pull_request, workflow_dispatch]

env:
  TF_LOG: INFO
  keyvaultname: "ghvaulttest"

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    # Set the working directory to main for the config files

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2

    - name: ConnectAzure
      uses: Azure/login@v1
      with:
        creds: ${{ secrets.KEYVAULT_CREDENTIALS }}

    - name: GetDeploymentSecret
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ env.keyvaultname }}
        secrets: testkey
      id: DeploymentSecret

    - name: Output
      run: | 
        echo "Key1 is ${{ steps.DeploymentSecret.outputs.testkey }}"

    - name: use output
      run: |
        echo $json_var | jq '.tenantId'
      env:
        json_var: ${{ steps.DeploymentSecret.outputs.testkey }}
        
    - name: ConnectAzureWithDeploymentCreds
      uses: Azure/login@v1
      with:
        creds: ${{ steps.DeploymentSecret.outputs.testkey }}

    - name: GetDeploymentSecret
      uses: Azure/get-keyvault-secrets@v1
      with: 
        keyvault: ${{ env.keyvaultname }}
        secrets: testkey2
      id: DeploymentSecret2

    - name: Output
      run: | 
        echo "Key2 is ${{ steps.DeploymentSecret2.outputs.testkey2 }}"